#!/usr/bin/env bash
#!/bin/bash
# script to display information about a domain and its subdomain

# variables & parameters
subdomains=( "www" "1b-01" "web-01" "web-02" )
domain="$1"
sub="$"

dig_cmd () {
        # func variables
        sub="$2"
        INFO="$(dig "$sub.$domain" | grep -Al 'ANSWER SECTION:' | awk 'NR==2')"
        IP=$(echo "$INFO" | awk '{print $5}')
        RECORD=$(echo "$INFO" | awk '{print $4}')

        echo -e "${brown} The subdomain ${blue}${sub${brown} is a ${blue}$RECORD${brown} record and points to ${blue}$IP${reset}"
}

if [ $#-eq 1 ]; then
        for subs in "${subdomains[@]}"; do
                dig_cmd "$domain" "$subs"
        done
elif [$# -eq 2 ]; then
        dig_cmd "$domain" "$sub"
fi
