#!/usr/bin/env bash
# a scrpt to install and configure HAProxy on 1b-01 server
# configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# make sure that HAProxy can be managed via an init script
# Install and configure Haproxy on my 1b-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend sisay-frontend
	bind *:80
	mode http
	default_backend sisay-backend
backend sisay-backend
	balance roundrobin
	server 94837-web-01 100.26.234.247:80 check
	server 94837-web-02 3.90.82.198:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/dafault/haproxy

sudo service haproxy restart
