#!/usr/bin/env bash
# debugging ngix port 80
# How I solved it: delet the existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/default. You do that by creating a symbolic link.
# note: the flag -s creates symbolic link, and -f deletes the existing file and replaces it
sudo ln -sf /ect/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
